services:
  frontend:
    image: frontend
    build:
      context: frontend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_URL=http://localhost:8001
    networks:
      - app-network
    depends_on:
      - backend
    restart: "no"

  backend:
    image: backend
    build:
      context: backend
    ports:
      - "8001:8001"
    volumes:
      - "./backend/src/week2:/app/src/week2"
      - "./backend/src/week2:/data"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MODEL=llama3.1
      - DB_PATH=/data/jobs.db
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate
    networks:
      - app-network
    restart: "no"

networks:
  app-network:
    driver: bridge