services:
  frontend:
    image: frontend
    build:
      context: frontend
    ports:
      - "8000:8000"
    secrets:
      - backend_url
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    image: backend
    build:
      context: backend
    ports:
      - "8001:8001"
    volumes:
      - "./backend/src/week2:/data"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - model
      - db_path
      - ollama_url
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

secrets:
  backend_url:
    external: true
  model:
    external: true
  db_path:
    external: true
  ollama_url:
    external: true